name: Deploy Prod #Name of the Workflow

on:
  workflow_dispatch:

jobs: #Workflow run is made up of one or more jobs
  deploy_lambda:
    runs-on: ubuntu-latest #Through which Server OS we need to Work (type of machine to run the job on)
    steps:
      #Using versioned actions
      - uses: actions/checkout@v2 # --> Reference a specific version
      - uses: actions/setup-node@v2 # --> To Setup the Server With Node Env
        with:
          node-version: "14" #--> Specify the Version of the Node

      - name: npm install
        env:
          CI: true
        run: |
          npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1 #--> Setup the Credential for the AWS cli
        with:
          # Created the Secrets Under the Repo only with These Variables
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} #--> Define Region of the AWS-CLI
      # Step 3: Install Terraform
      - name: Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      # Step 5: Initialize Terraform
      - name: Terraform Init
        run: terraform init
      # Step 6: Terraform Plan
      - name: Terraform Plan
        run: zip -j lambda_function.zip ./*
          terraform plan -var-file=terraform/prod.tfvars -chdir=terraform
      # Step 7: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -var-file=terraform/prod.tfvars -auto-approve -chdir=terraform
